version: "3"

services:
    client:
        container_name: foo
        build:
            context: .
            dockerfile: Dockerfile.client
        environment:
            QUERY_HOST: server
    server:
        container_name: bar
        build:
            context: .
            dockerfile: Dockerfile
