version: "3"

services:
    client:
        container_name: client
        build:
            context: .
            dockerfile: Dockerfile.client
        environment:
            QUERY_HOST: server
    server:
        container_name: server
        build:
            context: .
            dockerfile: Dockerfile
