FROM golang:1.18-alpine AS builder

WORKDIR /src
COPY go.mod .
COPY go.sum .
COPY *.go ./
COPY client luckless_client
RUN go build -o client luckless_client/main.go

FROM alpine

WORKDIR /app
COPY --from=builder /src/client .

CMD ./client