// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MarketDataClient is the client API for MarketData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketDataClient interface {
	Query(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*TimeSeries, error)
	QueryStream(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (MarketData_QueryStreamClient, error)
}

type marketDataClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataClient(cc grpc.ClientConnInterface) MarketDataClient {
	return &marketDataClient{cc}
}

func (c *marketDataClient) Query(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*TimeSeries, error) {
	out := new(TimeSeries)
	err := c.cc.Invoke(ctx, "/market.MarketData/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataClient) QueryStream(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (MarketData_QueryStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketData_ServiceDesc.Streams[0], "/market.MarketData/QueryStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataQueryStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketData_QueryStreamClient interface {
	Recv() (*DataPoint, error)
	grpc.ClientStream
}

type marketDataQueryStreamClient struct {
	grpc.ClientStream
}

func (x *marketDataQueryStreamClient) Recv() (*DataPoint, error) {
	m := new(DataPoint)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MarketDataServer is the server API for MarketData service.
// All implementations must embed UnimplementedMarketDataServer
// for forward compatibility
type MarketDataServer interface {
	Query(context.Context, *RangeRequest) (*TimeSeries, error)
	QueryStream(*RangeRequest, MarketData_QueryStreamServer) error
	mustEmbedUnimplementedMarketDataServer()
}

// UnimplementedMarketDataServer must be embedded to have forward compatible implementations.
type UnimplementedMarketDataServer struct {
}

func (UnimplementedMarketDataServer) Query(context.Context, *RangeRequest) (*TimeSeries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedMarketDataServer) QueryStream(*RangeRequest, MarketData_QueryStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method QueryStream not implemented")
}
func (UnimplementedMarketDataServer) mustEmbedUnimplementedMarketDataServer() {}

// UnsafeMarketDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServer will
// result in compilation errors.
type UnsafeMarketDataServer interface {
	mustEmbedUnimplementedMarketDataServer()
}

func RegisterMarketDataServer(s grpc.ServiceRegistrar, srv MarketDataServer) {
	s.RegisterService(&MarketData_ServiceDesc, srv)
}

func _MarketData_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/market.MarketData/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServer).Query(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketData_QueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServer).QueryStream(m, &marketDataQueryStreamServer{stream})
}

type MarketData_QueryStreamServer interface {
	Send(*DataPoint) error
	grpc.ServerStream
}

type marketDataQueryStreamServer struct {
	grpc.ServerStream
}

func (x *marketDataQueryStreamServer) Send(m *DataPoint) error {
	return x.ServerStream.SendMsg(m)
}

// MarketData_ServiceDesc is the grpc.ServiceDesc for MarketData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "market.MarketData",
	HandlerType: (*MarketDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _MarketData_Query_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "QueryStream",
			Handler:       _MarketData_QueryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "market.proto",
}
